const types = {
    GET_ALL_NOODLE_REQUEST:'GET_ALL_NOODLE_REQUEST',
    GET_ALL_NOODLE_SUCCSESS:'GET_ALL_NOODLE_SUCCSESS',
    GET_ALL_NOODLE_FAILURE:'GET_ALL_NOODLE_FAILURE',
    SO_LUOT_MUA:'SO_LUOT_MUA',
    
    

};

export default types;